services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 142536
      MYSQL_DATABASE: nodejs
    networks:
      - nodenet
    volumes:
      - ~/volumes/mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    networks:
      - nodenet

  web:
    image: nginx:latest
    container_name: web
    depends_on:
      - app
      - db
    networks:
      - nodenet
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  nodenet:
    driver: bridge
